menu:
- text: Presentación
  url: /
  target: _self
- text: Reuniones
  url: /reuniones
  target: _self
- text: Patrocinadores
  url: /patrocinadores
  target: _self
- text: Meetup
  url: https://www.meetup.com/es-ES/jsourense
  target: _blank
- text: Slack
  url: https://join.slack.com/t/javascript-ourense/shared_invite/enQtMjk2NjQyMzU0NTQ4LTA1ZjNiMDk3NGNhMTk3YjVjNzViNmM1NWVkZDZlMGQ5M2NjMjI2OGU3MDM1MTdhOTE0ZmUxMWI4ZGI5YzY2MTg
  target: _blank

favicon: /favicon/favicon-32x32.png
logo: /logo.png

# Copyright Infomation
startyear: 2018

# Analytics
google_analytics: UA-112261574-2
